version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: qr_web_server
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    networks:
      - qr_network

  db:
    image: mysql:8.0
    container_name: qr_database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: qr_tracker_db
      MYSQL_USER: qruser
      MYSQL_PASSWORD: qrpassword
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - qr_network

volumes:
  db_data:

networks:
  qr_network:
    driver: bridge